apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateways/internal/gateway.yaml
  - gateways/internal/virtual-services.yaml
  - gateways/public/gateway.yaml
  - gateways/public/virtual-services.yaml
